# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: 115.bel

on:
  schedule:
  - cron: "0 0 2 * 0"
  workflow_dispatch:
  
jobs:
  web-scraper-process:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: run parser
      run: |
        python get_data.py
    - uses: actions/upload-artifact@v2
      with: 
        name: parsing_results
        path: ./data
        retention-days: 5
        
    - uses: shallwefootball/s3-upload-action@master
      with:
        aws_key_id: ${{secrets.AWS_KEY_ID}}
        aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
        aws_bucket: 115bel
        source_dir: ./data
        
#       env:
#         KAGGLE_KEY: ${{secrets.KAGGLE_KEY}}
